### PR TITLE
Use the Unicode Consortium's character chart

### PR DESCRIPTION
**Pull request by sternenseemann**
Please let me know if I should change code style or documentation. Also note, that I haven't  checked yet, whether any names changed.

---

This chart is located at <http://www.unicode.org/emoji/charts/emoji-list.html>.
It contains more emojis (2419 instead of 842, almost three times as many)!

A few notes on the implementation:

* I considered using emoji-data, but parsing the website seemed easier
  than parsing the custom txt files <http://unicode.org/Public/emoji/5.0/>
* I did do quite a bit of bikeshedding and therefore decode the
  descriptions properly using UTF-8 although actually it only contains
  ASCII characters (I falsely assumed, that they also used Unicode chars)
* Performance has been reduced, but I guess this is fine.

### CODE REVIEW

**Comment by fxfactorial** [comment]
@sternenseemann This is awesome! Thank you! Question, is the new list a superset of the original one? 

EDIT: Just got a good idea for another PR, take the description and the emoji byte sequence itself and put it in a doc string, `(** *)` right before the identifier, then would be cute in things like `company-popup` in emacs, hopefully the emoji shows up in IDE or whenever generated into HTML documentation and such.

**Comment by sternenseemann** [comment]
I am pretty sure, that it is a superset indeed, but not entirely sure. I am currently in the process of checking the renames and removes, but it is a long and tedious process. I will post the results here later!

I could then introduce a (manually added) compatibility layer, do you think that is a good idea?

**Comment by fxfactorial** [comment]
Actually don't worry about that effort, this is great as is. 

What do you think about that other idea I wrote about? Would you like to do it or I will :) 

merged, thank you!

**Comment by sternenseemann** [comment]
I'll look at the other idea, seems like a nice idea!

**Comment by sternenseemann** [comment]
For the sake of completeness, these are all the changes, I had time to look at:

* smiling_face_with_open_mouth_and_tightly_closed_eyes -> smiling_face_with_open_mouth_and_closed_eyes
* smiling_face_with_heart_shaped_eyes -> smiling_face_with_heart_eyes
* smiling_face_with_heart_shaped_eyes -> smiling_face_with_heart_eyes
* smiling_cat_face_with_heart_shaped_eyes -> smiling_cat_face_with_heart_eyes
* face_throwing_a_kiss -> face_blowing_a_kiss
* face_with_stuck_out_tongue_and_tightly_closed_eyes -> face_with_stuck_out_tongue_and_tightly_closed_eyes
* face_with_look_of_triumph -> face_with_steam_from_nose
* face_with_no_good_gesture -> person_gesturing_no
* face_with_ok_gesture -> person_gesturing_ok 
* person_bowing_deeply -> person_bowing
* happy_person_raising_one_hand -> person_raising_hand
* person_raising_both_hands_in_celebration -> raising_hands
* person_with_pouting_face -> person_pouting
* person_with_folded_hands -> folded_hands
* black_scissors -> scissors
* eight_pointed_black_star -> eight_pointed_star
* negative_squared_cross_mark -> cross_mark_button
* black_question_mark_ornament -> question_mark
* white_question_mark_ornament -> white_question_mark
* white_exclamation_mark_ornament -> white_exclamation_mark
* heavy_black_heart -> black_heart
* black_rightwards_arrow -> right_arrow
* recreational_vehicle -> sport_utility_vehicle
* construction_sign -> construction
* police_cars_revolving_light -> oncoming_police_car
* triangular_flag_on_post -> triangular_flag
* no_entry_sign -> no_entry
* smoking_symbol -> cigarette
* no_smoking_symbol -> no_smoking
* pedestrian -> person_walking
* mens_symbol-> men_s_room
* womens_symbol -> women_s_room
* bath -> person_taking_bath
* circled_latin_capital_letter_m -> circled_m
* negative_squared_latin_capital_letter_a -> a_button_blood_type_
* negative_squared_latin_capital_letter_b -> b_button_blood_type_
* negative_squared_latin_capital_letter_o -> o_button_blood_type_
* negative_squared_latin_capital_letter_p -> p_button
* negative_squared_ab -> ab_button_blood_type_
* squared_cl -> cl_button
* squared_cool -> cool_button
* squared_free -> free_button
* squared_id -> id_button
* squared_new -> new_button
* squared_ng -> ng_button
* squared_ok -> ok_button
* squared_sos -> sos_button
* squared_up_with_exclamation_mark -> up_button
* squared_vs -> vs_button
* regional_indicator_symbol_letter_d___regional_indicator_symbol_letter_e -> germany
* regional_indicator_symbol_letter_g___regional_indicator_symbol_letter_b -> united_kingdom
* likewise for other countries as well
* squared_katakana_koko -> japanese_here_button
* squared_katakana_katakana_sa -> japanese_service_charge_button
* heavy_exclamation_mark_symbol -> **missing**

I found one removal, so it is not a superset, but I only found one until now.

**Comment by fxfactorial** [comment]
Ha, this is more intuitive: `regional_indicator_symbol_letter_d___regional_indicator_symbol_letter_e -> germany`

**Comment by sternenseemann** [comment]
So the removal I found, what should we do about it? It is pretty similar to another emoji (and has no corresponding question-mark one), so I suppose, it was removed in some standard, not sure though.

**Comment by fxfactorial** [comment]
I'm inclined to be okay with missing emojis, up to you if you want to add them back somehow.

**Pull request merged**
